CREATE TABLE IF NOT EXISTS rss_files (
  FileId INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  FileName CHARACTER VARYING(50) NOT NULL UNIQUE,
  SourceName CHARACTER VARYING(20) NOT NULL,
  RequestDate INT NOT NULL
);

CREATE TABLE IF NOT EXISTS files_checks (
  FileId INT PRIMARY KEY,
  FileExist BOOLEAN DEFAULT FALSE,
  FileNotEmpty BOOLEAN DEFAULT FALSE,
  FileFormat BOOLEAN DEFAULT FALSE,
  CONSTRAINT fk_file
    FOREIGN KEY(FileId)
	REFERENCES rss_files(FileId)
	ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS news_categories (
  CategoryId INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CategoryName CHARACTER VARYING(50) NOT NULL UNIQUE
);
